-- 0003: users (Phase 2). Every row of someone's data carries their user_id, and Postgres
-- row-level security hides other people's rows, so a query that forgets to filter by user
-- returns nothing rather than someone else's games.
--
-- How a connection acts for a user (db.connect(user_id=...)): it switches to the
-- knightly_app role, which has no right to bypass row-level security, and sets app.user_id.
-- New rows get that user_id by default, and the policies below only show rows that have it.
-- Connections that don't (migrations, `knightly users`, the shared puzzle import) keep the
-- login role, which owns the tables and sees everything.
--
-- Everything already here belongs to the one person who ran Knightly before it had users:
-- the "local" user, whose clerk_id `knightly users link` replaces with their Clerk id.

CREATE TABLE users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clerk_id    TEXT NOT NULL UNIQUE,   -- Clerk's user id ("user_2abc..."), or "local"
    created_at  TEXT NOT NULL DEFAULT iso_now()
);

INSERT INTO users (clerk_id)
SELECT 'local' WHERE EXISTS (SELECT 1 FROM accounts) OR EXISTS (SELECT 1 FROM games)
                  OR EXISTS (SELECT 1 FROM runs) OR EXISTS (SELECT 1 FROM settings)
                  OR EXISTS (SELECT 1 FROM puzzle_attempts);

-- The user this connection acts for; NULL when it acts for no one.
CREATE FUNCTION app_user() RETURNS integer LANGUAGE sql STABLE
    AS $$ SELECT nullif(current_setting('app.user_id', true), '')::integer $$;

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['accounts', 'games', 'puzzle_attempts', 'snapshots', 'sync_state',
                             'game_analysis', 'moves', 'runs', 'settings', 'engine_lines', 'cards',
                             'game_reviews', 'card_reviews'] LOOP
        EXECUTE format('ALTER TABLE %I ADD COLUMN user_id INTEGER REFERENCES users ON DELETE CASCADE', t);
        EXECUTE format('UPDATE %I SET user_id = (SELECT id FROM users WHERE clerk_id = %L)', t, 'local');
        -- NOT NULL + the default: a row written without a user fails instead of belonging to no one.
        EXECUTE format('ALTER TABLE %I ALTER COLUMN user_id SET NOT NULL, ALTER COLUMN user_id SET DEFAULT app_user()', t);
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('CREATE POLICY own_rows ON %I USING (user_id = app_user()) WITH CHECK (user_id = app_user())', t);
    END LOOP;
END $$;

-- Natural keys are now per user: two people who played each other both keep the game.
ALTER TABLE accounts DROP CONSTRAINT accounts_pkey, ADD PRIMARY KEY (user_id, source, handle);
ALTER TABLE games DROP CONSTRAINT games_source_source_id_key, ADD UNIQUE (user_id, source, source_id);
ALTER TABLE puzzle_attempts DROP CONSTRAINT puzzle_attempts_source_puzzle_id_attempted_at_key,
    ADD UNIQUE (user_id, source, puzzle_id, attempted_at);
ALTER TABLE sync_state DROP CONSTRAINT sync_state_pkey, ADD PRIMARY KEY (user_id, source, account, kind);
ALTER TABLE settings DROP CONSTRAINT settings_pkey, ADD PRIMARY KEY (user_id, key);
ALTER TABLE moves DROP CONSTRAINT moves_pkey, ADD PRIMARY KEY (user_id, game_id, ply);

-- Indexes lead with user_id, since every query a user makes filters by it.
DROP INDEX games_played_at, games_opening, games_outcome, puzzle_attempts_at, card_reviews_at,
           moves_user_class;
CREATE INDEX games_user_played_at ON games (user_id, played_at);
CREATE INDEX puzzle_attempts_user_at ON puzzle_attempts (user_id, attempted_at);
CREATE INDEX card_reviews_user_at ON card_reviews (user_id, reviewed_at);
CREATE INDEX moves_user_class ON moves (user_id, is_user, classification);
CREATE INDEX snapshots_user ON snapshots (user_id);
CREATE INDEX game_analysis_user ON game_analysis (user_id);
CREATE INDEX runs_user ON runs (user_id, id);
CREATE INDEX cards_user ON cards (user_id);
CREATE INDEX game_reviews_user ON game_reviews (user_id);
CREATE INDEX engine_lines_user ON engine_lines (user_id);

-- The role user connections switch to. Roles belong to the whole server, so it may exist.
DO $$ BEGIN
    CREATE ROLE knightly_app NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
GRANT knightly_app TO CURRENT_USER;
GRANT USAGE ON SCHEMA public TO knightly_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO knightly_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO knightly_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO knightly_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO knightly_app;
-- Users are managed by the server (sign-in, deletion), and the puzzle catalogue is shared and
-- read-only for users; neither has per-user rows.
REVOKE ALL ON users, schema_migrations FROM knightly_app;
REVOKE INSERT, UPDATE, DELETE ON lichess_puzzles FROM knightly_app;
