-- 0004: the job queue (Phase 3). Work that takes minutes (syncing an account, analysing
-- games) is a row here, and `knightly worker` processes run it: any number of them, on any
-- machine, each claiming the next job with FOR UPDATE SKIP LOCKED so no two get the same one.
--
-- kind: update   sync every account of the user, analyse their newest games, tag patterns
--       backfill analyse the next batch of older games, at a lower priority, so one person's
--                long history doesn't hold up everyone else's daily update
-- A user has at most one waiting or running job of each kind: asking again is a no-op.

CREATE TABLE jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL DEFAULT app_user() REFERENCES users ON DELETE CASCADE,
    kind        TEXT NOT NULL,                  -- update | backfill
    payload     TEXT,                           -- JSON, e.g. {"trigger": "manual"}
    priority    SMALLINT NOT NULL DEFAULT 0,    -- higher runs first
    status      TEXT NOT NULL DEFAULT 'queued', -- queued | running | done | failed
    attempts    SMALLINT NOT NULL DEFAULT 0,
    run_after   TEXT NOT NULL DEFAULT iso_now(),  -- a retry waits until then
    locked_by   TEXT,                           -- the worker running it
    locked_at   TEXT,
    error       TEXT,
    created_at  TEXT NOT NULL DEFAULT iso_now(),
    finished_at TEXT
);

-- What a worker looks for first; and the one-pending-job-per-kind rule.
CREATE INDEX jobs_next ON jobs (priority DESC, id) WHERE status = 'queued';
CREATE UNIQUE INDEX jobs_one_pending ON jobs (user_id, kind) WHERE status IN ('queued', 'running');
CREATE INDEX jobs_user ON jobs (user_id, id);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY own_rows ON jobs USING (user_id = app_user()) WITH CHECK (user_id = app_user());
